apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    {{- range .Values.labels }}
    {{ .name }}: "{{ .value }}"
    {{- end }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
  type: ClusterIP